config/routes.rb
# Plugin's routes
get 'projects/:project_id/remedy',
  :to => 'remedy_view#index',
  :as => 'remedy_tickets'

get 'projects/:project_id/remedy/:id',
  :to => 'remedy_view#show',
  :as => 'remedy_ticket'

post 'projects/:project_id/remedy/:id/new_issue',
  :to => 'remedy_view#new_issue',
  :as => 'remedy_ticket_new_issue'

delete '/projects/:project_id/remedy/settings/filter/:id',
  :to => 'remedy_view_config#destroy',
  :as => 'remedy_filter'

post '/projects/:project_id/remedy/settings/filter',
  :to => 'remedy_view_config#create',
  :as => 'project_remedy_filters'

app/models/remedy_filter.rb
class RemedyFilter < ActiveRecord::Base
  unloadable

  belongs_to :project

  validates :project_id,      :presence => true
  validates :title,           :presence => true
  validates :group,           :presence => true
#  validates :contract_number, :presence => true

  validates :title,           :uniqueness => { :scope => :project_id }
  validates :contract_number, :uniqueness => { :scope => [ :project_id, :group ] }

  scope :project_filters, ->(project) {
    where(:project_id => project.is_a?(Project) ? project.id : project)
    .order('title')
  }
end

app/models/remedy_ticket.rb
class RemedyTicket < ActiveRecord::Base
  unloadable

  attr_reader :sla_response, :sla_restore, :sla_resolve, :sla_nccd

  has_many :remedy_ticket_issues
  has_many :issues, :through => :remedy_ticket_issues

  scope :by_remedy_filter, ->(filter) {
    contract = filter.contract_number == '' ? nil : filter.contract_number
    where(:owner_group => filter.group, :contract_number => contract)
  }

  scope :open, -> { where('state < ?', 6) }
  scope :sorted, -> { order(:remedy_id) }

  SLA_OK = 0
  SLA_ACTION = 1
  SLA_WARN = 2
  SLA_OVERDUE = 3

  def contact_phone
    unless contact_country_code.nil? || contact_country_code.empty?
      "+#{contact_country_code} #{contact_local_number}"
    else
      contact_local_number
    end
  end

  def state_s
    case state
      when 0 then "New"
      when 1 then "Assigned"
      when 2 then "Re-Assigned"
      when 3 then "In Progress"
      when 4 then "Pending"
      when 5 then "Resolved"
      when 6 then "Closed"
      else "Unknown"
    end
  end

  def severity_s
    "Sev. " + severity.to_s
  end

  def priority_s
    case priority
      when 1 then "Emergency"
      when 2 then "High"
      when 3 then "Medium"
      when 4 then "Low"
      else priority.to_s
    end
  end

  def calculate_sla
    now = Time.now
    # FIXME: configurable thresholds
    @sla_response = calculate_single_sla(actual_respond_date, target_respond_date, now, 15*60)
    @sla_restore = calculate_single_sla(actual_restore_date, target_restore_date, now, 6*60*60)
    @sla_resolve = calculate_single_sla(actual_resolve_date, target_resolve_date, now, 24*60*60)

    if state >= 6
      @sla_nccd = ""
    elsif next_customer_contact_date.nil?
      @sla_nccd = "overdue"
    elsif now > next_customer_contact_date
      @sla_nccd = "warn"
    elsif now + 24*60*60 > next_customer_contact_date
      @sla_nccd = "action-required"
    else
      @sla_nccd = ""
    end
  end

  def sla_overall
    map_sla(@sla)
  end

  private

  def calculate_single_sla(actual, target, now, threshold)
    sla = SLA_OK
    unless target.nil?
      if actual.nil?
        if now > target
          sla = SLA_OVERDUE
        elsif now + threshold > target
          sla = SLA_WARN
        else
          sla = SLA_ACTION
        end
      elsif actual > target
       sla = SLA_OVERDUE
      end
    end
    @sla = sla if @sla.nil? || sla > @sla
    map_sla(sla)
  end

  def map_sla(sla)
    case sla
      when SLA_ACTION  then "action-required"
      when SLA_WARN    then "warn"
      when SLA_OVERDUE then "overdue"
      else ""
    end
  end
end

app/models/remedy_ticket_issue.rb
class RemedyTicketIssue < ActiveRecord::Base
  unloadable

  belongs_to :issue
  belongs_to :remedy_ticket
  belongs_to :project

  validates :remedy_ticket_id, :presence => true
  validates :project_id,       :presence => true

  validates :issue_id,         :uniqueness => { :scope => :remedy_ticket_id  }
end

app/controllers/remedy_view_config_controller.rb
class RemedyViewConfigController < ApplicationController
  unloadable

  before_filter :find_project_by_project_id, :authorize

  def create
    @remedy_filter = RemedyFilter.new
    @remedy_filter.title = params[:remedy_filter][:title]
    @remedy_filter.group = params[:remedy_filter][:group]
    @remedy_filter.contract_number = params[:remedy_filter][:contract_number]
    @remedy_filter.project = @project

    if @remedy_filter.save
      @new_filter_id = @remedy_filter.id
      @remedy_filter = RemedyFilter.new
    end

    respond_to do |format|
      format.html { redirect_to settings_project_path(@project, 'remedy_view') }
      format.js { render :action => "show" }
    end
  end

  def destroy
    filter = RemedyFilter.find(params[:id])
    return render_403 unless @project.id == filter.project_id

    filter.destroy

    respond_to do |format|
      format.html { redirect_to settings_project_path(@project, 'remedy_view') }
      format.js { render :action => "show" }
    end
  end
end

app/controllers/remedy_view_controller.rb
class RemedyViewController < ApplicationController
  unloadable

  before_filter :find_project_by_project_id
  before_filter :authorize

  helper :watchers
  helper :projects
  helper :issues
  helper :custom_fields

  def index
    @ticket_groups = []
    RemedyFilter.project_filters(@project).each do |filter|
      @ticket_groups << {
        :filter => filter,
        :tickets => RemedyTicket.by_remedy_filter(filter).open().sorted()
      }
    end
  end

  def show
    @ticket = RemedyTicket.includes(:issues).find(params[:id])
    @ticket.calculate_sla
    @allowed_projects = Project.allowed_to(User.current, :add_issues)

    setup_new_issue(@project)
  end

  def new_issue
    @ticket = RemedyTicket.find(params[:id])

    project = Project.find(params[:issue][:project_id])
    setup_new_issue(project)

    # need to override @project for the issue to be created in the right project
    @project = project
  end

  private

  def setup_new_issue(project)
    rel = RemedyTicketIssue.new
    rel.project = @project
    rel.remedy_ticket = @ticket

    # mostly from IssuesController#build_new_issue_from_params
    @issue = Issue.new
    @issue.remedy_ticket_issues << rel
    @issue.project = project
    @issue.author = User.current
    @issue.subject = @ticket.short_description
    @issue.tracker = project.trackers.first
    @issue.start_date = Date.today if Setting.default_issue_start_date_to_creation_date?

    @priorities = IssuePriority.active
    @allowed_statuses = @issue.new_statuses_allowed_to(User.current, @issue.new_record?)
    @available_watchers = @issue.watcher_users
    if @issue.project.users.count <= 20
      @available_watchers = (@available_watchers + @issue.project.users.sort).uniq
    end
  end
end

app/helpers/remedy_view_helper.rb
module RemedyViewHelper
end

app/views/issues/_remedy_ticket_form.html.erb
<%= form.fields_for :remedy_ticket_issues do |f| %>
  <%= f.hidden_field :project_id %>
  <%= f.hidden_field :remedy_ticket_id %>
<% end %>

app/views/issues/_remedy_tickets.html.erb
<% if issue.remedy_ticket_issues.any? %>
  <% content_for :header_tags do -%>
    <%= stylesheet_link_tag "remedy_view.css", :plugin => :redmine_remedy_view %>
  <% end -%>

  <hr>
  <p><strong><%=l(:label_issues_related_remedy_tickets)%></strong></p>
  <table class="list issues remedy-relations">
    <% issue.remedy_ticket_issues.each do |rel| %>
      <tr class="issue" id="remedy-<%= rel.remedy_ticket.remedy_id %>">
        <td class="id">
          <%= h(rel.project) %>&nbsp;-&nbsp;
          <%= link_to rel.remedy_ticket.remedy_id,
                remedy_ticket_path(rel.project, rel.remedy_ticket_id) %>
        </td>
        <td class="subject"><%= rel.remedy_ticket.short_description %></td>
        <td class="status"><%= rel.remedy_ticket.state_s %></td>
        <td class="assignee"><%= rel.remedy_ticket.assignee %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/remedy_view/_issue_remedy_ticket.html.erb
<%= form.fields_for :remedy_ticket_issues do |f| %>
  <%= f.hidden_field :project_id %>
  <%= f.hidden_field :remedy_ticket_id %>
<% end %>

app/views/remedy_view/index.html.erb
<% content_for :header_tags do -%>
  <%= stylesheet_link_tag "remedy_view.css", :plugin => :redmine_remedy_view %>
<% end -%>

<h2><%= l(:label_remedy_view_tickets) %></h2>

<div class="autoscroll">
  <table class="list issues remedy">
    <thead>
      <tr>
        <th>AR #</th>
        <th>
          <%= l(:field_created_on) %><br>
          <%= l(:field_updated_on) %>
        </th>
        <th>TS</th>
        <th><%= l(:field_remedy_ticket_nccd) %></th>
        <th>
          <%= l(:field_remedy_ticket_severity) %><br>
          <%= l(:field_remedy_ticket_priority) %>
        </th>
        <th>
          <%= l(:field_remedy_ticket_state) %><br>
          <span class="remedy-smaller"><%= l(:field_remedy_ticket_state_reason) %></span>
        </th>
        <th>
          <%= l(:field_remedy_ticket_short_description) %><br>
          <span class="remedy-smaller"><%= l(:field_remedy_ticket_current_summary) %></span>
        </th>
        <th>
          <%= l(:field_assigned_to) %><br>
          <%= l(:field_remedy_ticket_last_modified_by) %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @ticket_groups.each do |tg| %>
        <% reset_cycle %>
        <% if @ticket_groups.length > 1 %>
          <tr class="group open">
            <td colspan="8">
              <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
              <%= tg[:filter].title %>
              <span class="count"><%= tg[:tickets].length %></span>
              <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}",
                                   "toggleAllRowGroups(this)", :class => 'toggle-all') %>
            </td>
          </tr>
        <% end %>
        <% tg[:tickets].each do |t| %>
          <% t.calculate_sla %>
          <tr class="<%= cycle('odd', 'even') %>">
            <td class="id">
              <%= link_to t.remedy_id, remedy_ticket_path(@project, t) %>
            </td>
            <td class="created_on">
              <%= format_time(t.actual_reported_date) %><br>
              <%= format_time(t.last_modified_on) %>
            </td>
            <td>
              <span class="remedy <%= t.sla_overall %>"></span>
            </td>
            <td title="<%= format_time(t.next_customer_contact_date) %>">
              <span class="remedy <%= t.sla_nccd %>"></span>
            </td>
            <td class="priority">
              <%= t.severity_s %><br>
              <%= t.priority_s %>
            </td>
            <td class="status">
              <%= t.state_s %><br>
              <span class="remedy-smaller"><%= t.state_reason %></span>
            </td>
            <td class="subject">
              <%= link_to t.short_description , remedy_ticket_path(@project, t) %><br>
              <div class="remedy-current-summary"><%= t.current_summary %></div>
            </td>
            <td class="assigned_to">
              <%= t.assignee %><br>
              <%= t.last_modified_by %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/remedy_view/new_issue.js.erb
try {
  $('#remedy2issue').show().html('<%= escape_javascript(render :template => 'issues/new.html') %>');
} catch (err) {
}
var h2 = $('#remedy2issue > h2');
h2.text("<%= @project %> - " + h2.text());
hideOnLoad();

app/views/remedy_view/show.html.erb
<% content_for :header_tags do -%>
  <%= stylesheet_link_tag "remedy_view.css", :plugin => :redmine_remedy_view %>
<% end -%>

<% my_title = l(:label_remedy_view_ticket) + " AR " + @ticket.remedy_id %>
<% title my_title %>
<h2><%= my_title %></h2>

<div class="issue">
  <div class="subject">
    <h3><%= @ticket.short_description %></h3>
  </div>
  <p class="author">
    <%= l(:label_remedy_view_ticket_added_by) %>
    <strong><%= @ticket.contact_surname %>, <%= @ticket.contact_given_name %></strong>
    <%= l(:label_remedy_view_ticket_added_via) %>
    "<%= @ticket.request_method %>"
  </p>
  <table class="attributes">
    <tr>
      <th><%= l(:field_created_on) %></th>
      <td><%= format_time(@ticket.actual_reported_date) %></td>
      <th><%= l(:field_remedy_ticket_severity) %> / <%= l(:field_remedy_ticket_priority) %></th>
      <td><%= @ticket.severity_s %> / <%= @ticket.priority_s %></td>
    </tr>
    <tr>
      <th><%= l(:field_remedy_ticket_request_type) %></th>
      <td><%= @ticket.request_type %></td>
      <th><%= l(:field_remedy_ticket_request_category) %></th>
      <td><%= @ticket.request_category %></td>
    </tr>
    <tr>
      <th><%= l(:field_remedy_ticket_state) %></th>
      <td><%= @ticket.state_s %></td>
      <th><%= l(:field_remedy_ticket_state_reason) %></th>
      <td><%= @ticket.state_reason %></td>
    </tr>
    <tr>
      <th><%= l(:field_remedy_ticket_site_company) %></th>
      <td><%= @ticket.site_company %></td>
      <th><%= l(:field_remedy_ticket_site) %></th>
      <td><%= @ticket.site %></td>
    </tr>
    <tr>
      <th><%= l(:field_remedy_ticket_contact_company) %></th>
      <td><%= @ticket.contact_company %></td>
      <th><%= l(:field_remedy_ticket_contact_email) %></th>
      <td><%= mail_to(h(@ticket.contact_email)) %></td>
    </tr>
    <tr>
      <th><%= l(:field_remedy_ticket_contact_phone) %></th>
      <td><%= @ticket.contact_phone %></td>
      <th><%= l(:field_remedy_ticket_contact_additional) %></th>
      <td><%= Redmine::WikiFormatting.to_html("null", @ticket.additional_contact_info || "") %></td>
    </tr>
    <tr>
      <th><%= l(:field_assigned_to) %></th>
      <td><%= @ticket.assignee %></td>
      <th><%= l(:field_updated_on) %></th>
      <td>
        <%= format_time(@ticket.last_modified_on) %>
        / <%= @ticket.last_modified_by %>
      </td>
    </tr>
    <tr>
      <th><%= l(:field_remedy_ticket_product) %></th>
      <td><%= @ticket.product %></td>
      <th><%= l(:field_remedy_ticket_product_version) %></th>
      <td><%= @ticket.product_version %></td>
    </tr>
    <tr>
      <th><%= l(:field_remedy_ticket_model) %></th>
      <td><%= @ticket.model %></td>
      <th><%= l(:field_remedy_ticket_customer_ticket) %></th>
      <td><%= @ticket.customer_ticket %></td>
    </tr>
  </table>
  <hr>

  <table class="attributes">
    <tr>
      <th><%= l(:field_remedy_ticket_actual_respond_date) %></th>
      <td class="remedy <%= @ticket.sla_response %>">
        <%= format_time(@ticket.actual_respond_date) %>
      </td>
      <th><%= l(:field_remedy_ticket_target_respond_date) %></th>
      <td><%= format_time(@ticket.target_respond_date) %></td>
    </tr>
    <tr>
      <th><%= l(:field_remedy_ticket_actual_restore_date) %></th>
      <td class="remedy <%= @ticket.sla_restore %>">
        <%= format_time(@ticket.actual_restore_date) %>
      </td>
      <th><%= l(:field_remedy_ticket_target_restore_date) %></th>
      <td><%= format_time(@ticket.target_restore_date) %></td>
    </tr>
    <tr>
      <th><%= l(:field_remedy_ticket_actual_resolve_date) %></th>
      <td class="remedy <%= @ticket.sla_resolve %>">
        <%= format_time(@ticket.actual_resolve_date) %>
      </td>
      <th><%= l(:field_remedy_ticket_target_resolve_date) %></th>
      <td><%= format_time(@ticket.target_resolve_date) %></td>
    </tr>
    <tr>
      <th><%= l(:field_remedy_ticket_actual_closed_date) %></th>
      <td><%= format_time(@ticket.actual_closed_date) %></td>
      <th>&nbsp;</th>
      <td>&nbsp;</td>
    </tr>
  </table>
  <hr>

  <table class="attributes">
    <tr>
      <th><%= l(:field_remedy_ticket_next_customer_contact_date) %></th>
      <td class="remedy <%= @ticket.sla_nccd %>">
        <%= format_time(@ticket.next_customer_contact_date) %>
      </td>
    </tr>
    <tr>
      <th><%= l(:field_remedy_ticket_current_summary) %></th>
      <td>&nbsp;</td>
      <th>&nbsp;</th>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td colspan="4">
        <div class="wiki">
          <%= @ticket.current_summary %>
        </div>
      </td>
    </tr>
  </table>
  <hr>

  <p><strong><%=l(:label_remedy_view_redmine_issues)%></strong></p>
  <form>
    <table class="list issues remedy">
      <% @ticket.issues.each do |issue| %>
        <tr class="issue" id="issue-<%= issue.id %>">
          <td class="subject">
            <%= h(issue.project) + ' - ' %>
            <%= link_to_issue(issue, :truncate => 60) %>
          </td>
          <td class="status"><%=h issue.status.name %></td>
          <td class="assignee"><%=h issue.assigned_to %></td>
          <td class="start_date"><%= format_date(issue.start_date) %></td>
          <td class="due_date"><%= format_date(issue.due_date) %></td>
        </tr>
      <% end %>
    </table>
  </form>

  <%= form_for :issue,
        :url => remedy_ticket_new_issue_path(@project, @ticket.id),
        :remote => true do |f| %>
    <p>
      <%= l(:label_remedy_view_add_redmine_issue) %>
      <%= f.select :project_id,
            project_tree_options_for_select(@allowed_projects, :selected => @project) %>
      <%= f.submit l(:button_add) %>
    </p>
  <% end %>
</div>

<div id="remedy2issue" style="display: none;">
  <%= render :template => 'issues/new' %>
</div>

app/views/remedy_view_config/_show.html.erb
<div class="splitcontentleft">
  <% remedy_filters = RemedyFilter.project_filters(@project) %>
  <% if remedy_filters.any? %>
    <table class="list">
      <thead>
        <tr>
          <th><%= l(:field_remedy_filter_title) %></th>
          <th><%= l(:field_remedy_filter_group) %></th>
          <th><%= l(:field_remedy_filter_contract) %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% remedy_filters.each do |filter| %>
          <tr id="remedy_filter-<%= filter.id %>" class="<%= cycle 'odd', 'even' %>">
            <td><%= filter.title %></td>
            <td><%= filter.group %></td>
            <td><%= filter.contract_number %></td>
            <td class="buttons">
              <%= link_to(l(:button_delete), remedy_filter_path(@project, filter), :data => { :confirm => l(:text_are_you_sure)},
                :method => :delete, :class => 'icon icon-del') %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% end %>
</div>

<div class="splitcontentright">
  <div class="box tabular">
    <% @remedy_filter ||= RemedyFilter.new %>
    <%= labelled_form_for [@project, @remedy_filter], :remote => true do |f| %>
      <p><%= f.text_field :title, :required => true,
           :label => :field_remedy_filter_title %></p>
      <p><%= f.text_field :group, :required => true,
           :label => :field_remedy_filter_group %></p>
      <p><%= f.text_field :contract_number, :required => true,
           :label => :field_remedy_filter_contract %></p>
      <%= submit_tag l(:button_create) %>
    <% end %>
  </div>
</div>

app/views/remedy_view_config/show.js.erb
$('#tab-content-remedy_view').html('<%= escape_javascript(render :partial => 'show') %>');
hideOnLoad();

<% if @new_filter_id.present? %>
  $("#remedy_filter-<%= @new_filter_id %>").effect("highlight");
<% end %>